---
title: "Articles"
permalink: /articles/
author_profile: true
output: github_document
---
```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(RefManageR)
library(tidyverse)

bib <- ReadBib(paste0(getwd(),"/REFERENCES.bib"))
bib_p <- bib[grepl("preprint",bib$keywords)] # preprint
yn <- year(now())
bib_p <- bib_p[bib_p$year %in% c(yn-1,yn)]
bib_a <- bib[bibtype = "Article"] # articles
year <- bib_a$year %>% unique() %>% unlist() %>% as.integer() %>% sort(decreasing = T)


```
Cette page contient des [pré-prints](#preprints) (articles en cours de revision dans une revue scientifique) et des
[publications revues par les pairs](#publications-revues-par-les-pairs) (publiées dans une revue).

Accès par années (article puliés dans une revue) : 
```{r results = "asis", echo = FALSE}
for (y in year){
  cat(paste0("[",y,"](#",y,")\n"))
}
```

## Preprints
```{r results = "asis", echo = FALSE}
# print
NoCite(bib_p)
temp_file <- tempfile()
txt <- capture.output(PrintBibliography(bib_p,  .opts = list(check.entries = FALSE,
                                     bib.style = "authoryear",
                                           style = "markdown",
                                     no.print.fields = c("urldate","issn"),
                                           sorting = "ydnt")), file = temp_file)
  clean <- clean_bib(temp_file)
  writeLines(clean, temp_file, useBytes = TRUE)
  writeLines(readLines(temp_file))
  cat("\n")
  
```


## Publications revues par les pairs
```{r results = "asis", echo = FALSE}
# print
for (y in year){
  cat(paste("###",y,"\n"))
  bib_y <- bib_a[year = as.character(y)]
  NoCite(bib_y)
  temp_file <- tempfile()
  txt <- capture.output(PrintBibliography(bib_y,  .opts = list(check.entries = FALSE,
                                     bib.style = "authoryear",
                                           style = "markdown",
                                     no.print.fields = c("urldate","issn"),
                                           sorting = "none")), file = temp_file)
  clean <- clean_bib(temp_file)
  writeLines(clean, temp_file, useBytes = TRUE)
  writeLines(readLines(temp_file))
  cat("\n")
}

```

